  enemySpawning[m
  feature/enemy-movement[m
  feature/enemy-movement-old[m
  feature/enemy-waves[m
  feature/health-bar[m
  feature/player-enemy-interactions[m
  feature/player-movement[m
  feature/powerup-effects[m
  feature/powerup-handler-testing[m
  feature/powerup-spawning[m
  feature/pubsub[m
  feature/sound-effects[m
  feature/state-pattern-screens[m
  feature/testing-setup[m
* [32mmain[m
  tests/powerup-handler-tests[m
  [31mremotes/origin/debt/cleaning-stats-panel[m
  [31mremotes/origin/enemySpawning[m
  [31mremotes/origin/feature/enemy-movement[m
  [31mremotes/origin/feature/enemy-shooting-update[m
  [31mremotes/origin/feature/enemy-waves[m
  [31mremotes/origin/feature/health-bar[m
  [31mremotes/origin/feature/health-testing[m
  [31mremotes/origin/feature/passing-enemies-deal-damage[m
  [31mremotes/origin/feature/player-enemy-interactions[m
  [31mremotes/origin/feature/player-movement[m
  [31mremotes/origin/feature/powerup-effects[m
  [31mremotes/origin/feature/powerup-handler-testing[m
  [31mremotes/origin/feature/powerup-spawned[m
  [31mremotes/origin/feature/powerup-spawning[m
  [31mremotes/origin/feature/pubsub[m
  [31mremotes/origin/feature/sound-effects[m
  [31mremotes/origin/feature/state-pattern-screens[m
  [31mremotes/origin/feature/stats-testing[m
  [31mremotes/origin/feature/stats-tracker[m
  [31mremotes/origin/feature/testing-setup[m
  [31mremotes/origin/main[m
  [31mremotes/origin/tests/powerup-handler-tests[m
